import localFont from "next/font/local";
import {Montserrat} from "next/font/google";
import "./globals.css";
import Nav from "./_components/Nav";



const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  fallback: ["Helvetica", "Arial", "sans-serif"],
});



export const metadata = {
  title: "BerryCare App",
  description: "Generated by create BerryCare app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-montserrat antialiased`}
      >
        <Nav/>
        {children}
      </body>
    </html>
  );
}
